dist: xenial
language: python
sudo: required
python:
  - '3.7'
addons:
  apt:
    update: true
    packages:
      - jq
      - awscli
install:
    - make bootstrap
    - install-terraform --terraform-version 0.12.24
script:
    - make test
deploy:
    skip_cleanup: true
    provider: script
    script: terraform-cd --module-version $TRAVIS_TAG revdb-terraform-modules
    on:
        branch: master
        tags: true
